name: Tests Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run Tests
    runs-on: windows-latest

    steps:
      - name: Checkout the repositroy 
        uses: actions/checkout@v2
      - name: Install the needed packages and integrate with Applitools
        run: |
          npm install
          echo 'set APPLITOOLS_API_KEY=XCTPPI8fOt1108dWho9M1zC1jEK2eg1BPrAY88LW105c7Uk110'
      - name: Install testcafe 
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome test"
